CREATE TABLE HELLOWORLD(
  HELLO VARCHAR(20) NOT NULL,
  WORLD VARCHAR(15),
  DIALECT VARCHAR(15) NOT NULL,
  PRIMARY KEY(DIALECT)

);

CREATE TABLE HELLOWORLD2(
  HELLO VARCHAR(20),
  WORLD VARCHAR(15),
  DIALECT VARCHAR(15),
  NAME VARCHAR(20)

);


PARTITION TABLE HELLOWORLD ON COLUMN DIALECT;
CREATE PROCEDURE FROM CLASS Insert;
CREATE PROCEDURE FROM CLASS Insert2;
CREATE PROCEDURE FROM CLASS Select;
CREATE PROCEDURE FROM CLASS Inner;
PARTITION PROCEDURE Insert ON TABLE Helloworld COLUMN Dialect;
PARTITION PROCEDURE Select ON TABLE Helloworld COLUMN Dialect;
